### ISSUE TITLE
Receive a 500 when attempting to retire a package

### ISSUE THREAD

**Issue by anthonator** [wojtekmach/mini_repo#15]
When attempting to retire a package I get the following error.

```
2019-10-31T12:12:27.108306+00:00 app[web.1]: 12:12:27.104 [error] GenServer :<repo> terminating
2019-10-31T12:12:27.108308+00:00 app[web.1]: ** (KeyError) key :reason not found in: %{"message" => "Not wanted", "reason" => "other"}
2019-10-31T12:12:27.108311+00:00 app[web.1]: (stdlib) :maps.get(:reason, %{"message" => "Not wanted", "reason" => "other"})
2019-10-31T12:12:27.108313+00:00 app[web.1]: (elixir) lib/map.ex:273: Map.update!/3
2019-10-31T12:12:27.108316+00:00 app[web.1]: (mini_repo) lib/mini_repo/repository/server.ex:52: anonymous fn/4 in MiniRepo.Repository.Server.retire/4
2019-10-31T12:12:27.108319+00:00 app[web.1]: (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
2019-10-31T12:12:27.108321+00:00 app[web.1]: (mini_repo) lib/mini_repo/repository/server.ex:50: anonymous fn/3 in MiniRepo.Repository.Server.retire/4
2019-10-31T12:12:27.108324+00:00 app[web.1]: (elixir) lib/map.ex:780: Map.update!/3
2019-10-31T12:12:27.108326+00:00 app[web.1]: (mini_repo) lib/mini_repo/repository/server.ex:98: MiniRepo.Repository.Server.update_registry/3
2019-10-31T12:12:27.108329+00:00 app[web.1]: (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
2019-10-31T12:12:27.108331+00:00 app[web.1]: Last message (from #PID<0.5322.0>): {:update, #Function<3.17456623/1 in MiniRepo.Repository.Server.retire/4>}
2019-10-31T12:12:27.108337+00:00 app[web.1]: State: #MiniRepo.Repository<name: "<repo>", public_key: "<public key>", registry: %{"hello_repo" => [...]}, store: {...}, ...>
2019-10-31T12:12:27.108339+00:00 app[web.1]: Client #PID<0.5322.0> is alive
2019-10-31T12:12:27.108342+00:00 app[web.1]: 
2019-10-31T12:12:27.108344+00:00 app[web.1]: (stdlib) gen.erl:167: :gen.do_call/4
2019-10-31T12:12:27.108346+00:00 app[web.1]: (elixir) lib/gen_server.ex:1006: GenServer.call/3
2019-10-31T12:12:27.108348+00:00 app[web.1]: (mini_repo) lib/mini_repo/api_router.ex:52: anonymous fn/5 in MiniRepo.APIRouter.do_match/4
2019-10-31T12:12:27.108351+00:00 app[web.1]: (mini_repo) lib/plug/router.ex:259: MiniRepo.APIRouter.dispatch/2
2019-10-31T12:12:27.108353+00:00 app[web.1]: (mini_repo) lib/mini_repo/api_router.ex:1: MiniRepo.APIRouter.plug_builder_call/2
2019-10-31T12:12:27.108355+00:00 app[web.1]: (mini_repo) lib/mini_repo/endpoint.ex:1: MiniRepo.Endpoint.plug_builder_call/2
2019-10-31T12:12:27.108357+00:00 app[web.1]: (plug_cowboy) lib/plug/cowboy/handler.ex:12: Plug.Cowboy.Handler.init/2
2019-10-31T12:12:27.108359+00:00 app[web.1]: (cowboy) /usr/local/mini_repo/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
2019-10-31T12:12:27.108361+00:00 app[web.1]: 
2019-10-31T12:12:27.108364+00:00 app[web.1]: 12:12:27.106 [error] #PID<0.5322.0> running MiniRepo.Endpoint (connection #PID<0.5321.0>, stream id 1) terminated
2019-10-31T12:12:27.108366+00:00 app[web.1]: Server: <host>:80 (http)
2019-10-31T12:12:27.108368+00:00 app[web.1]: Request: POST /api/repos/<repo>/packages/hello_repo/releases/0.0.0/retire
2019-10-31T12:12:27.10837+00:00 app[web.1]: ** (exit) exited in: GenServer.call(:<repo>, {:update, #Function<3.17456623/1 in MiniRepo.Repository.Server.retire/4>}, 5000)
2019-10-31T12:12:27.108372+00:00 app[web.1]: ** (EXIT) an exception was raised:
2019-10-31T12:12:27.108375+00:00 app[web.1]: ** (KeyError) key :reason not found in: %{"message" => "Not wanted", "reason" => "other"}
2019-10-31T12:12:27.108377+00:00 app[web.1]: (stdlib) :maps.get(:reason, %{"message" => "Not wanted", "reason" => "other"})
2019-10-31T12:12:27.108379+00:00 app[web.1]: (elixir) lib/map.ex:273: Map.update!/3
2019-10-31T12:12:27.108381+00:00 app[web.1]: (mini_repo) lib/mini_repo/repository/server.ex:52: anonymous fn/4 in MiniRepo.Repository.Server.retire/4
2019-10-31T12:12:27.108384+00:00 app[web.1]: (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
2019-10-31T12:12:27.108386+00:00 app[web.1]: (mini_repo) lib/mini_repo/repository/server.ex:50: anonymous fn/3 in MiniRepo.Repository.Server.retire/4
2019-10-31T12:12:27.108387+00:00 app[web.1]: (elixir) lib/map.ex:780: Map.update!/3
2019-10-31T12:12:27.10839+00:00 app[web.1]: (mini_repo) lib/mini_repo/repository/server.ex:98: MiniRepo.Repository.Server.update_registry/3
2019-10-31T12:12:27.108392+00:00 app[web.1]: (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
```

**Comment by wojtekmach** [comment]
Fixed on master, thank you for the report!
