### ISSUE TITLE
Inner checksum upload and outer checksum download errors with Hex > 0.20.5

### ISSUE THREAD

**Issue by asummers** [wojtekmach/mini_repo#21]
I believe related to the discussion in https://github.com/hexpm/hex/issues/753 and the subsequent work in https://github.com/wojtekmach/mini_repo/tree/wm-outer-checksum

When downloading a dependency of the form `{:my_dep, "~> 1.2.3", repo: "my_repo"},` `mix deps.get` results in the error: 

```
** (RuntimeError) Checksum mismatch against registry (outer)
    (hex) lib/hex/scm.ex:187: Hex.SCM.update/1
    (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:190: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:123: Mix.Dep.Converger.all/7
    (mix) lib/mix/dep/converger.ex:108: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
```

and when publishing via `mix hex.publish`, the logs print 

```
HTTP status code: 500
Publishing failed
```

with the server logs:
```
18:20:14.875 [error] GenServer :risk terminating
** (stop) {:gpb_type_error, {{:missing_fields, [:inner_checksum], :Release}, [value: %{checksum: <<36, 164, 185, 217, 137, 83, 6, 217, 75, 0, 242, 235, 245, 170, 228, 97, 27, 58, 170, 34, 185, 252, 155, 12, 123, 196, 155, 128, 244, 121, 136, 236>>, dependencies: [REDACTED], version: "1.2.3"}, path: :"Package.releases"]}}
    (hex_core) /build/deps/hex_core/src/hex_pb_package.erl:1426: :hex_pb_package.mk_type_error/3
    (hex_core) /build/deps/hex_core/src/hex_pb_package.erl:1247: :hex_pb_package."-v_msg_Package/3-lc$^0/1-0-"/3
    (hex_core) /build/deps/hex_core/src/hex_pb_package.erl:1248: :hex_pb_package.v_msg_Package/3
    (hex_core) /build/deps/hex_core/src/hex_pb_package.erl:64: :hex_pb_package.encode_msg/3
    (mini_repo) lib/mini_repo/registry_builder.ex:70: MiniRepo.RegistryBuilder.build_package/3
    (mini_repo) lib/mini_repo/registry_builder.ex:23: MiniRepo.RegistryBuilder.build_partial/3
    (mini_repo) lib/mini_repo/repository/server.ex:129: MiniRepo.Repository.Server.build_partial_registry/2
    (mini_repo) lib/mini_repo/repository/server.ex:113: MiniRepo.Repository.Server.update_registry/3
```

**Comment by asummers** [comment]
The problem seems to source from a mixture of packages with checksum and inner_checksum. Adding the following `Enum.map` to `MiniRepo.RegistryBuilder.build_package/3` causes packages to publish without error but I am not convinced that this is the correct thing to do.  

```elixir
  def build_package(repository, name, releases) do
    releases =
      Enum.map(releases, fn release ->
        if Map.has_key?(release, :checksum) do
          release
          |> Map.put(:inner_checksum, release.checksum)
          |> Map.delete(:checksum)
        else
          release
        end
      end)

    protobuf =
      :hex_registry.encode_package(%{repository: repository.name, name: name, releases: releases})

    sign_and_gzip(repository, protobuf)
  end
```

**Comment by asummers** [comment]
Note that doing the above results in `mix deps.get` errors on `inner_checksum` mismatches that I have not figured out. Guidance  here on how `mini_repo` is supposed to play with the `inner_checksum` and friends would be welcome.

**Comment by asummers** [comment]
This is no longer an issue if you start your data fresh. In my case, that meant destroying the S3 bucket and letting the folder resync. That is unsatisfying as far as migrations, but things seem to be working with your WIP branch.
